FROM node:22-alpine
RUN npm install -g pnpm

WORKDIR /app
COPY pnpm-workspace.yaml package.json ./
COPY apps/api/package.json ./apps/api/
COPY packages/types/package.json ./packages/types/
RUN pnpm install --frozen-lockfile

COPY apps/api ./apps/api
COPY packages ./packages

WORKDIR /app/apps/api
CMD ["node", "--watch", "--import", "tsx/esm", "src/index.ts"]
